/**
 * ⚠️ AUTO-GENERATED FILE
 *
 * This file is automatically generated by:
 * `scripts/sync-provider-types.ts`
 *
 * Do not modify this file manually.
 */

export type ProviderType =
  | "anthropic"
  | "gemini"
  | "groq"
  | "huggingface"
  | "openai"

export interface Config {
  provider: ProviderType
  apiKey: string
  model: string
}

export interface AIProvider {
  generateCommitMessage(
    diff: string,
    options?: { regenerate?: boolean }
  ): Promise<string>
}
