import fs from "fs"
import path from "path"

const PROVIDERS_DIR = path.resolve(process.cwd(), "src/providers/ai")
const TYPES_DIR = path.resolve(process.cwd(), "src/types")
const TYPES_FILE = path.join(TYPES_DIR, "index.ts")

export function syncProviderTypes() {
  const providerFiles = fs
    .readdirSync(PROVIDERS_DIR)
    .filter(
      (file) =>
        file.endsWith(".ts") && file !== "index.ts" && !file.startsWith(".")
    )

  const providers = providerFiles
    .map((file) => path.basename(file, ".ts"))
    .sort()

  const content = `/**
 * ⚠️ AUTO-GENERATED FILE
 *
 * This file is automatically generated by:
 * \`scripts/sync-provider-types.ts\`
 *
 * Do not modify this file manually.
 */

export type ProviderType =
${providers.map((provider) => `  | "${provider}"`).join("\n")}

export interface Config {
  provider: ProviderType
  apiKey: string
  model: string
}

export interface AIProvider {
  generateCommitMessage(
    diff: string,
    options?: { regenerate?: boolean }
  ): Promise<string>
}
`

  // Ensure directory exists
  fs.mkdirSync(TYPES_DIR, { recursive: true })

  // Create or overwrite file
  fs.writeFileSync(TYPES_FILE, content, "utf8")

  console.log("✓ src/types/index.ts synced successfully")
}

syncProviderTypes()
