import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme.provider";
import { Navbar } from "@/components/shared/navbar";
import { fontVariable } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={fontVariable("h-full font-sans antialiased")}
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider>
          <Navbar />
          {props.children}
        </ThemeProvider>
      </body>
    </html>
  );
}
