import type { Metadata } from "next";
import "./globals.css";
import { SoundFxProvider } from "@/components/providers/sound.provider";
import { ThemeProvider } from "@/components/providers/theme.provider";
import { Navbar } from "@/components/shared/navbar";
import { fontVariable } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={fontVariable("h-full font-sans antialiased")}
    >
      <body className="flex min-h-full flex-col">
        <SoundFxProvider>
          <ThemeProvider>
            <Navbar />
            {props.children}
          </ThemeProvider>
        </SoundFxProvider>
      </body>
    </html>
  );
}
